CREATE TABLE STREAM ( ID INTEGER PRIMARY KEY,
SRCNUM INT , DSTNUM INT,
DESCRIPTION TEXT,
SRCDATA BLOB, DSTDATA BLOB,
SRCBODY BLOB, DSTBODY BLOB,
FOREIGN KEY(SRCNUM) REFERENCES SRCHOST(SRCNUM),
FOREIGN KEY(DSTNUM) REFERENCES DSTHOST(DSTNUM) );
CREATE TABLE SRCHOST( SRCNUM INTEGER PRIMARY KEY,
SRCIP CHAR(20) UNIQUE);
CREATE TABLE DSTHOST( DSTNUM INTEGER PRIMARY KEY,
DSTIP CHAR(20) UNIQUE);
create table SRCHEADER ( COLUMNID INTEGER PRIMARY KEY,COLUMNATTR TEXT );
create table DSTHEADER ( COLUMNID INTEGER PRIMARY KEY,COLUMNATTR TEXT );
